# Generated by CMake, DO NOT EDIT
CMakeFiles/cmake.check_cache: \
/Users/kail/imClever/dev/virtualSkin/CMakeLists.txt\
/Users/kail/imClever/dev/virtualSkin/xcode/CMakeFiles/CMakeCCompiler.cmake\
/Users/kail/imClever/dev/virtualSkin/xcode/CMakeFiles/CMakeCXXCompiler.cmake\
/Users/kail/imClever/dev/virtualSkin/xcode/CMakeFiles/CMakeSystem.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCInformation.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCXXInformation.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeCommonLanguageInclude.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeGenericSystem.cmake\
/opt/local/share/cmake-2.8/Modules/CMakeSystemSpecificInformation.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/GNU-C.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/GNU-CXX.cmake\
/opt/local/share/cmake-2.8/Modules/Compiler/GNU.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-GNU-C.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-GNU-CXX.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin-GNU.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/Darwin.cmake\
/opt/local/share/cmake-2.8/Modules/Platform/UnixPaths.cmake
	/opt/local/bin/cmake -H/Users/kail/imClever/dev/virtualSkin -B/Users/kail/imClever/dev/virtualSkin/xcode
